### ISSUE TITLE
Add presentation from NCEI WCSD Archive 2022 workshop

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/group-docs#21]

**Comment by leewujung** [comment]
Wrong repo for this issue? 😉

**Comment by leewujung** [comment]
> `group-docs` and `group-website` are awfully similar 

Maybe we should rename one of them....?

**Comment by emiliom** [comment]
Maybe. Probably not worth it, though

**Comment by leewujung** [comment]
Haha, ok, let's keep it as is for now.
